### PR TITLE
Add better interface for subscription updates

### PR DESCRIPTION
**Pull request by brysgo**
I got some feedback from @kristianmandrup about the promise iterator being less than easy to use. I added a wrapper around it inspired by `co.wrap`.

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Good stuff :)

You should check out this [Jafar Husain Netflix presentation](https://www.youtube.com/watch?v=3pKNRgResq0) on async function iteration patterns in future Javascript, however the original proposal has been [withdrawn](https://github.com/babel/babel/issues/2082) and replaced by [Observer proposal](https://github.com/tc39/proposal-observable) due to some [Monadic purity objections](https://news.ycombinator.com/item?id=13210849) (hackernews)

There are Babel plugins for [transform](https://babeljs.io/docs/plugins/transform-async-generator-functions/) and [syntax](https://babeljs.io/docs/plugins/syntax-async-generators/) however...

**Comment by amark** [comment]
Wow, @brysgo sounds like you've been a BUSY BEAST! :O :D :)

**Comment by brysgo** [comment]
Lol, it may look crazier than it is, I just added semantic-release so I'm not sure how accurate it's understanding of the first release it does is :-)

**Pull request merged**
